spring.jpa.hibernate.ddl-auto=create

server.port=0

spring.cloud.function.definition=customerSupplier

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema/schema.sql
#NOTE: don't forget to add  supply in the line 12 in order to make those pollers commented to work
#spring.cloud.stream.bindings.publish-out-0.producer.useNativeEncoding=true
#spring.cloud.stream.bindings.publish-out-0..producer.poller.fixed-delay=6000

#spring.cloud.stream.kafka.binder.producerProperties.value.serializer=org.springframework.kafka.support.serializer.JsonSerializer