spring.datasource.url=jdbc:mysql://localhost:3306/Customer
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=create-drop

server.port=8283

spring.cloud.function.definition=customerSupplier

spring.cloud.stream.bindings.customerSupplier-out-0.destination=customer-topic
spring.cloud.stream.bindings.publish-out-0.destination=customer-topic

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema/schema.sql

spring.mvc.problemdetails.enabled=true

spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.externalization.enabled=true
spring.modulith.events.kafka.enable-json=true
spring.modulith.moments.locale=pt
spring.modulith.events.republish-outstanding-events-on-restart=true

#NOTE: don't forget to add  supply in the line 12 in order to make those pollers commented to work
#spring.cloud.stream.bindings.publish-out-0.producer.useNativeEncoding=true
#spring.cloud.stream.bindings.publish-out-0..producer.poller.fixed-delay=6000

spring.kafka.producer.key-serializer=org.springframework.kafka.support.serializer.StringOrBytesSerializer
spring.cloud.stream.kafka.binder.producerProperties.key.serializer=org.apache.kafka.common.serialization.StringSerializer